const SOURCES = {
  wattgpu: {
    label: 'WattGPU: Predicting Inference Power and Latency on Unseen GPUs and LLMs',
    ref: 'Fadel Argerich et al., IJCAI 2026 workshop',
    url: 'https://arxiv.org/abs/2607.02391',
    cat: 'preprint',
    note: 'Predicts GPU power draw and inter-token latency across 42 open LLMs (0.1B-27B) x 8 GPUs. Basis for per-token power assumptions.',
  },
  tokensToWh: {
    label: 'From Tokens to Watt-hours: Analytical Energy Estimation for LLM Inference on Modern GPUs',
    ref: 'Vartziotis et al., GREEN-AI @ ECML-PKDD 2026',
    url: 'https://arxiv.org/abs/2607.26571',
    cat: 'preprint',
    note: 'Analytic energy estimator on H100-class accelerators; separates prompt prefill from autoregressive decoding and compute from memory energy.',
  },
  langEnergy: {
    label: 'The Language-Energy Divide: Measuring Energy Costs of Multilingual LLM Inference',
    ref: 'Deng et al., 2026',
    url: 'https://arxiv.org/abs/2606.21869',
    cat: 'preprint',
    note: 'Measured energy per output token; per-request energy varies up to 179x across languages (English 17.6 kJ vs Pashto 3,147 kJ).',
  },
  videoEnergy: {
    label: 'Video Killed the Energy Budget: Characterizing the Latency and Power Regimes of Open Text-to-Video Models',
    ref: 'Delavande, Pierrard & Luccioni, NeurIPS 2025 NextVid Workshop',
    url: 'https://arxiv.org/abs/2509.19222',
    cat: 'preprint',
    note: 'Measured (CodeCarbon, H100): ~90 Wh per short video for WAN2.1-T2V-1.3B (720x1280, 81 frames, 50 steps), ~415 Wh for the 14B flagship. Video is ~30x image generation, ~2,000x text generation.',
  },
  vllmConfigs: {
    label: 'Attention to Detail: Energy, Performance and Accuracy Trade-offs Across vLLM Configurations',
    ref: 'Zine et al., 2026',
    url: 'https://arxiv.org/abs/2607.09172',
    cat: 'preprint',
    note: '9,000 runs / 93,600 energy measurements. Model choice dominates global energy trade-offs.',
  },
  hymell: {
    label: 'Multi-Level Modeling of LLM Inference Latency and Energy (HYMELL)',
    ref: 'Shokoufa et al., 2026',
    url: 'https://arxiv.org/abs/2608.06723',
    cat: 'preprint',
    note: 'Hybrid analytical/ML energy model; <5% error for LLaMA-3-8B prefill and decode on H100.',
  },
  aiServers: {
    label: 'The Environmental Impact of AI Servers and Sustainable Solutions',
    ref: 'Patel, Mahalingam & Patel, 2025',
    url: 'https://arxiv.org/abs/2601.06063',
    cat: 'preprint',
    note: 'Global data-center electricity 415 TWh (2024) to ~945 TWh (2030). US AI servers add 200-300B gal water/yr and 24-44 Mt CO2e by 2030.',
  },
  concentratedSiting: {
    label: 'Concentrated Siting of AI Data Centers Drives Regional Power-System Stress',
    ref: 'Chen et al., 2026',
    url: 'https://arxiv.org/abs/2604.06198',
    cat: 'preprint',
    note: 'Six leading AI firms: ~118 TWh (2024) rising to 239-295 TWh (2030).',
  },
  edgeNative: {
    label: 'Separating Intelligence from Inference: A Standard for Edge-Native AI Computing',
    ref: 'Vinjam & Narukulla, 2026',
    url: 'https://arxiv.org/abs/2608.02608',
    cat: 'preprint',
    note: 'Fully edge-resident inference for 1B daily users saves ~19 TWh/yr and ~7.3 Mt CO2 vs centralized practice.',
  },
  strubell2019: {
    label: 'Energy and Policy Considerations for Deep Learning in NLP',
    ref: 'Strubell, Ganesh & McCallum, ACL 2019',
    url: 'https://arxiv.org/abs/1906.02243',
    cat: 'peer',
    note: 'Foundational peer-reviewed measurement: training a large transformer can emit ~284 t CO2e; established the NLP energy-cost agenda (ACL 2019).',
  },
  llmcarbon: {
    label: 'LLMCarbon: Modeling the end-to-end Carbon Footprint of Large Language Models',
    ref: 'Faiz et al., ICLR 2024',
    url: 'https://arxiv.org/abs/2309.14393',
    cat: 'peer',
    note: 'Peer-reviewed end-to-end carbon model for dense and MoE LLMs (training + inference + embodied); improves on mlco2. ICLR 2024.',
  },
  asrCompare: {
    label: 'Comparative Analysis of Energy Consumption and Carbon Footprint in Automatic Speech Recognition Systems',
    ref: 'El Bahri, Kouissi & Achkari Begdouri, Computer Sciences & Mathematics Forum 2025, 10(1):6',
    url: 'https://www.mdpi.com/2813-0324/10/1/6',
    cat: 'peer',
    note: 'Measured Whisper (local) vs Google Speech-to-Text (cloud) on 20,000 clips / ~22.2 h of audio. Cloud STT used ~51% less energy (~0.35 kWh total) and ~42% less CO2 than locally-run Whisper.',
  },
  ieaEnergyAI: {
    label: 'IEA, Energy and AI',
    ref: 'IEA, April 2025',
    url: 'https://www.iea.org/reports/energy-and-ai',
    cat: 'institution',
    note: 'Data-center electricity ~415 TWh in 2024, projected to reach ~945 TWh by 2030.',
  },
  ieaKeyQuestions: {
    label: 'IEA, Key Questions on Energy and AI',
    ref: 'IEA, April 2026',
    url: 'https://www.iea.org/reports/key-questions-on-energy-and-ai',
    cat: 'institution',
    note: '2026 IEA flagship follow-up on AI electricity demand.',
  },
  conversation: {
    label: "Your AI habit is wasting precious resources. Here's how to use it responsibly",
    ref: 'Seyedali Mirjalili, The Conversation, June 2026',
    url: 'https://theconversation.com/your-ai-habit-is-wasting-precious-resources-heres-how-to-use-it-responsibly-285065',
    cat: 'journalism',
    note: 'The "truck carrying one envelope" framing: use the right tool for the task. Cites IEA ~945 TWh by 2030; links to EESI water data.',
  },
  eesiWater: {
    label: 'Data Centers and Water Consumption',
    ref: 'Miguel Yañez-Barnuevo, EESI, June 2025',
    url: 'https://www.eesi.org/articles/view/data-centers-and-water-consumption',
    cat: 'institution',
    note: 'Every 100-word AI prompt ~1 bottle (~519 ml) water (UC Riverside); avg WUE 1.9 L/kWh; large DCs up to 5M gal/day (~town of 10-50k); ~110M gal/yr medium DC (~1,000 households); ~80% of withdrawn water evaporates.',
  },
  industryAu: {
    label: 'Expectations of data centres and AI infrastructure developers',
    ref: 'Australian Government, Dept of Industry, Science and Resources, March 2026',
    url: 'https://www.industry.gov.au/publications/expectations-data-centres-and-ai-infrastructure-developers',
    cat: 'institution',
    note: 'Five national expectations: national interest, energy transition, sustainable water use, skills/jobs, research & local capability. Non-genuine proposals deprioritised.',
  },
  sbsNews: {
    label: 'Amid new guidelines, a warning data centres could "cut corners", threaten energy, water supply',
    ref: 'Cameron Carr, SBS News, March 2026',
    url: 'https://www.sbs.com.au/news/article/new-expectations-in-place-for-resource-hungry-data-centres-coming-to-australia/9cqgj2cdj',
    cat: 'journalism',
    note: 'IEA: ChatGPT ~2.9 Wh/query (~10x Google search); ~0.5 L water per 20-50 queries. Altman counter-claim ~0.34 Wh. AU data centres ~2% of grid energy tripling to ~6% by 2030; expectations voluntary, not law.',
  },
  cellReports: {
    label: 'The carbon and water footprints of data centers and what this could mean for artificial intelligence',
    ref: 'Alex de Vries-Gao, Patterns 7 (2026) 101430, Cell Press',
    url: 'https://www.sciencedirect.com/science/article/pii/S2666389925002788',
    doi: '10.1016/j.patter.2025.101430',
    cat: 'peer',
    note: 'AI ~15-20% of total data-center electricity at end-2024; AI power demand 9.4 GW to 23 GW through 2025. AI carbon footprint 2025: 32.6-79.7 Mt CO2 (approx. New York City); AI water 312.5-764.6B L (approx. global bottled water). Indirect (electricity-embedded) water dominates: ~3.4 L/kWh actual vs ~1.04 L/kWh IEA-implied.',
  },
  powerHungry: {
    label: 'Power Hungry Processing: Watts Driving the Cost of AI Deployment?',
    ref: 'Luccioni, Jernite & Strubell, FAccT 2024',
    url: 'https://arxiv.org/abs/2311.16863',
    cat: 'peer',
    note: 'First systematic measurement of energy and carbon per 1,000 inferences for generative vs task-specific models.',
  },
  thirsty: {
    label: 'Making AI Less "Thirsty": Uncovering and Addressing the Secret Water Footprint of AI Models',
    ref: 'Li et al., Communications of the ACM, 2025 (arXiv 2023)',
    url: 'https://arxiv.org/abs/2304.03271',
    cat: 'peer',
    note: 'ChatGPT conversation of 20-50 prompts ~500 ml water; GPT-3 training ~700,000 L. Peer-reviewed in Communications of the ACM.',
  },
  devries: {
    label: 'The Growing Energy Footprint of Artificial Intelligence',
    ref: 'de Vries, Joule 7(10), 2023',
    url: 'https://doi.org/10.1016/j.joule.2023.02.010',
    cat: 'peer',
    note: '~2.9 Wh per ChatGPT query and ~0.3 Wh per Google search. Widely cited headline figures, since disputed as overestimates. Peer-reviewed (Joule).',
  },
  cloudCarbon: {
    label: 'Estimating the Size and Impact of ChatGPT',
    ref: 'Cloud Carbon Footprint, 2024',
    url: 'https://www.cloudcarbonfootprint.org/reports/estimating-the-size-and-impact-of-chatgpt/',
    cat: 'journalism',
    note: 'ChatGPT ~8.3 g CO2e per query on average; GPT-3.5 ~4 g, GPT-4 ~15 g. Industry report, not peer-reviewed.',
  },
  openaiPrice: {
    label: 'OpenAI API pricing',
    ref: 'OpenAI',
    url: 'https://developers.openai.com/api/docs/models',
    cat: 'vendor',
    note: 'GPT-5.6 line (per 1M tokens): Sol $5/$30 (1.05M context, cutoff Feb 2026), Terra $2/$12, Luna $0.20/$1.20. GPT-5.4/5.5 also listed.',
  },
  gptImagePrice: {
    label: 'GPT Image API pricing',
    ref: 'OpenAI / costgoat per-image calculators',
    url: 'https://costgoat.com/pricing/openai-images',
    cat: 'vendor',
    note: 'Per 1024x1024 image: GPT Image 1 low ~$0.011, medium ~$0.042, high ~$0.167; Mini $0.005-$0.052. This dashboard uses the medium tier (~$0.04/image).',
  },
  videoPrice: {
    label: 'AI video generation API pricing',
    ref: 'cometapi / fluxnote / devtk 2026 comparisons',
    url: 'https://www.cometapi.com/ai-video-api-pricing/',
    cat: 'vendor',
    note: 'Per-second rates $0.03-$0.70 (Kling ~$0.07/s, Sora ~$0.10/s, Veo ~$0.40/s). A ~5-8 s clip is roughly $0.5-$2; this dashboard uses ~$1.00/clip as a mid-range estimate.',
  },
  anthropicPrice: {
    label: 'Anthropic API pricing',
    ref: 'Anthropic',
    url: 'https://www.anthropic.com/pricing',
    cat: 'vendor',
    note: 'Claude 5 line (per 1M tokens): Fable 5 $10/$50, Opus 5 $5/$25, Sonnet 5 $2/$10, Haiku 4.5 $1/$5. Legacy Sonnet 4.5 $3/$15.',
  },
  googlePrice: {
    label: 'Gemini API pricing',
    ref: 'Google AI',
    url: 'https://ai.google.dev/gemini-api/docs/pricing',
    cat: 'vendor',
    note: 'List prices per 1M tokens. Gemini 3 Pro price could not be re-verified (page timed out during research); shown as an approximation.',
  },
  deepseekPrice: { label: 'DeepSeek API pricing', ref: 'DeepSeek', url: 'https://api-docs.deepseek.com/quick_start/pricing', cat: 'vendor', note: 'List prices per 1M tokens.' },
  epaEg: { label: 'EPA eGRID: U.S. grid CO2 intensity', ref: 'EPA eGRID, 2024', url: 'https://www.epa.gov/egrid', cat: 'institution', note: 'U.S. average ~386 g CO2e/kWh.' },
  ieaGrid: { label: 'Electricity emissions intensity', ref: 'IEA', url: 'https://www.iea.org/data-and-statistics', cat: 'institution', note: 'Australia ~500 g CO2e/kWh (IEA). The dashboard bases all CO2 calculations on this Australian grid intensity.' },
  ukGrid: {
    label: 'UK grid carbon intensity',
    ref: 'Energy Dashboard / Hoare Lea, 2025',
    url: 'https://www.energydashboard.co.uk/insights/2025-review',
    cat: 'institution',
    note: 'Great Britain 2025 average ~128 g CO2e/kWh (Energy Dashboard); Hoare Lea 129 gCO2e/kWh (Scope 2, generation-based).',
  },
  euGrid: {
    label: 'EU electricity generation intensity',
    ref: 'EEA, 2024 early estimate',
    url: 'https://www.eea.europa.eu/en/analysis/indicators/greenhouse-gas-emission-intensity-of-1',
    cat: 'institution',
    note: 'EU-27 power-generation intensity fell ~11% in 2024 (EEA early estimate) to ~250 g CO2e/kWh; ranges widely by member state (e.g. France ~51, Poland ~847).',
  },
  ecosiaHome: {
    label: 'Ecosia - the search engine that plants trees',
    ref: 'Ecosia GmbH',
    url: 'https://www.ecosia.org/',
    cat: 'vendor',
    note: '254.6M trees planted; 20M users; 100% of profits to climate; claims to produce more renewable energy than its searches and AI queries use. B-Corp, not-for-profit.',
  },
  ecosiaCo2: {
    label: "What's the CO2 impact of an Ecosia search?",
    ref: 'Christian Kroll, Ecosia blog, May 2018',
    url: 'https://blog.ecosia.org/co2-neutral-seach-engine-ecosia-solar-plant/',
    cat: 'vendor',
    note: 'First 531 kWp solar plant built 2017; claims every Ecosia search "removes CO2" via tree-planting profits and that servers run on 100% renewable energy.',
  },
  ecosiaAi: {
    label: "The world's greenest AI is here",
    ref: 'Ecosia blog, December 2025',
    url: 'https://blog.ecosia.org/ecosia-ai/',
    cat: 'vendor',
    note: 'AI Overviews + AI Chat launch. Uses smaller, more efficient models; avoids video generation; invests ~18M in renewables; uses AI Energy Score (HuggingFace) and Ecologits to select/track models.',
  },
  ecosiaAiImproved: {
    label: 'Our AI just got even better',
    ref: 'Ecosia blog, May 2026',
    url: 'https://blog.ecosia.org/improving-our-ai/',
    cat: 'vendor',
    note: 'Ecosia AI now runs almost entirely on a European model provider; describes a lighter, more energy-efficient footprint than mainstream models.',
  },
  ecosiaAiFree: {
    label: 'You can now choose AI-free search',
    ref: 'Ecosia blog, July 2026',
    url: 'https://blog.ecosia.org/ai-free-search/',
    cat: 'vendor',
    note: 'All Ecosia AI features are optional and can be switched off; user choice over AI use is a design principle.',
  },
  ecosiaRegen: {
    label: 'Ecosia Regeneration Report',
    ref: 'Ecosia GmbH',
    url: 'https://blog.ecosia.org/regeneration-report-24/',
    cat: 'vendor',
    note: 'Reports ~102 t CO2 annual organizational footprint; repeats the claim that each Ecosia search "removes 1 kg CO2" and that Ecosia produces twice as much renewable energy as its searches need.',
  },
  ecosiaFactCheck: {
    label: 'What specific numbers does Ecosia publish about AI energy use and CO2?',
    ref: 'Factually fact-check, April 2026',
    url: 'https://factually.co/fact-checks/environment/ecosia-latest-regeneration-report-ai-energy-use-co2-numbers-bef319',
    cat: 'journalism',
    note: 'Confirms Ecosia publishes aggregate totals (102 t CO2) but no per-query energy/CO2 for search or AI. Only explicit AI number: Ecosia estimate chatbot raises CO2 ~5% (~5.1 t on 102 t base). Critics call for per-query disclosure.',
  },
  unricAi: {
    label: 'UN Scientists: AI Is Threatening Natural Resources for Billions',
    ref: 'UNRIC / UNU-INWEH report, June 2026',
    url: 'https://unric.org/en/ais-environmental-costs-threaten-water-land-and-climate/',
    cat: 'institution',
    note: 'Global DC electricity 448 TWh (2025) -> 945 TWh (2030), ~9.3 trillion L water footprint by 2030. Inference ~80-90% of AI energy (not training). ChatGPT ~2.5B prompts/day ~383 GWh/yr. Chat query ~200x text classification; AI image ~1,450x (~29 ml water each); short video ~200,000x spam-classification. E-waste ~2.5M t/yr by 2030. Report: Aczel et al. 2026, doi:10.53328/INR26RMA002.',
  },
  wsjWater: {
    label: 'AI Data Centers Use Far More Water Than Most Tech Giants Report',
    ref: 'Christopher Mims, Wall Street Journal, 2026',
    url: 'https://www.wsj.com/tech/ai/ai-data-centers-water-use-901e2902',
    cat: 'journalism',
    note: 'Only Meta tallies indirect water used at the power plants feeding its data centres; no legal obligation to report full scope. US indirect water consumption ~12x the direct figure (Lawrence Berkeley National Laboratory, 2024). Companies spending ~$1T on AI infrastructure.',
  },
  dcByte: {
    label: 'Australian Data Centre Forecast Report',
    ref: 'Data Centres Australia & DC Byte, April 2026',
    url: 'https://www.dcbyte.com/industry-reports/australian-data-centre-forecast-report/',
    cat: 'journalism',
    note: 'Operational capacity ~1.4 GW now, forecast to ~3.2 GW by 2030, inside a ~21.6 GW announced pipeline.',
  },
  aemoDc: {
    label: 'AEMO discloses 5.4 GW Australian data centre pipeline',
    ref: 'Certified Strategic, June 2026',
    url: 'https://certifiedstrategic.com/insights/aemo-5-4gw-australian-data-centre-pipeline-june-2026',
    cat: 'journalism',
    note: 'AEMO first disclosure of data-centre capacity in the transmission connection queue: 11 projects, 5.4 GW, ~60% NSW / 40% Victoria.',
  },
  commbankDc: {
    label: "Australia's data centre boom: a $150 billion investment",
    ref: 'CommBank newsroom, August 2026',
    url: 'https://www.commbank.com.au/articles/newsroom/2026/08/australias-data-centre-boom.html',
    cat: 'journalism',
    note: '~6 GW potential pipeline, roughly 4x the operational capacity at end-2025; build-out could total ~$150B by 2030 and become the dominant driver of business investment growth.',
  },
  nineDc: {
    label: 'Map exposes bold data centre plan for Sydney and Melbourne',
    ref: 'Nine News, June 2026',
    url: 'https://www.nine.com.au/australia-news/map-exposes-australia-s-bold-plan-to-become-the-data-centre-capital-of-the-world-20260615-p606xw.html',
    cat: 'journalism',
    note: 'Over 160 data-centre facilities already operating across every state and territory; dozens more planned or in development, concentrated on Sydney and Melbourne boundaries.',
  },
};

const DATA = {
  grids: [
    { id: 'au', label: 'Australia (avg)', gCO2ePerKWh: 500, source: 'ieaGrid' },
    { id: 'us', label: 'United States (avg)', gCO2ePerKWh: 386, source: 'epaEg' },
    { id: 'uk', label: 'United Kingdom (avg)', gCO2ePerKWh: 128, source: 'ukGrid' },
    { id: 'eu', label: 'European Union (avg)', gCO2ePerKWh: 250, source: 'euGrid' },
  ],

  gridIntensity: {
    label: 'Australia (avg)',
    gCO2ePerKWh: 500,
    source: 'ieaGrid',
  },

  models: [
    {
      id: 'gpt56sol',
      name: 'GPT-5.6 Sol',
      provider: 'OpenAI',
      size: 'flagship reasoning model, ~1.05M context',
      gpuPowerW: 700,
      jPerInTok: 0.10,
      jPerOutTok: 1.6,
      priceInUsdPer1M: 5.00,
      priceOutUsdPer1M: 30.00,
      waterPerQueryMl: 5,
      reasoning: true,
      energyNote: 'decode-energy assumption (reasoning model; chain-of-thought, effort varies none-max)',
      sources: ['wattgpu', 'tokensToWh', 'langEnergy', 'openaiPrice', 'eesiWater', 'sbsNews', 'thirsty'],
    },
    {
      id: 'gpt56luna',
      name: 'GPT-5.6 Luna',
      provider: 'OpenAI',
      size: 'cost-optimized reasoning model',
      gpuPowerW: 400,
      jPerInTok: 0.03,
      jPerOutTok: 0.6,
      priceInUsdPer1M: 0.20,
      priceOutUsdPer1M: 1.20,
      waterPerQueryMl: 1.5,
      reasoning: true,
      energyNote: 'decode-energy assumption (reasoning model; compact tier)',
      sources: ['wattgpu', 'tokensToWh', 'openaiPrice', 'eesiWater', 'sbsNews', 'thirsty'],
    },
    {
      id: 'claude-sonnet-5',
      name: 'Claude Sonnet 5',
      provider: 'Anthropic',
      size: 'frontier reasoning model',
      gpuPowerW: 700,
      jPerInTok: 0.10,
      jPerOutTok: 1.4,
      priceInUsdPer1M: 2.00,
      priceOutUsdPer1M: 10.00,
      waterPerQueryMl: 5,
      reasoning: true,
      energyNote: 'decode-energy assumption (reasoning model; chain-of-thought)',
      sources: ['wattgpu', 'tokensToWh', 'langEnergy', 'anthropicPrice', 'eesiWater', 'sbsNews', 'thirsty'],
    },
    {
      id: 'gemini3',
      name: 'Gemini 3 Pro',
      provider: 'Google',
      size: 'frontier reasoning model (MoE)',
      gpuPowerW: 600,
      jPerInTok: 0.08,
      jPerOutTok: 1.3,
      priceInUsdPer1M: 2.00,
      priceOutUsdPer1M: 15.00,
      waterPerQueryMl: 4,
      reasoning: true,
      energyNote: 'decode-energy assumption (reasoning model; price approximate, see source note)',
      sources: ['wattgpu', 'tokensToWh', 'googlePrice', 'eesiWater', 'sbsNews', 'thirsty'],
    },
    {
      id: 'deepseekv3',
      name: 'DeepSeek-V3',
      provider: 'DeepSeek',
      size: '~671B params (MoE, ~37B active)',
      gpuPowerW: 700,
      jPerInTok: 0.07,
      jPerOutTok: 1.2,
      priceInUsdPer1M: 0.27,
      priceOutUsdPer1M: 1.10,
      waterPerQueryMl: 4,
      energyNote: 'decode-energy assumption (mid-range of 2026 published measurements)',
      sources: ['wattgpu', 'tokensToWh', 'deepseekPrice', 'eesiWater', 'sbsNews', 'thirsty'],
    },
  ],

  queryTypes: [
    { id: 'quick', label: 'Quick question', promptTok: 80, outTok: 200 },
    { id: 'standard', label: 'Standard answer', promptTok: 200, outTok: 400 },
    { id: 'detailed', label: 'Detailed / write code', promptTok: 500, outTok: 1000 },
    { id: 'long', label: 'Long context (RAG / document)', promptTok: 8000, outTok: 800 },
    { id: 'vision', label: 'Image / vision input', promptTok: 1500, outTok: 150 },
  ],

  referenceCards: [
    { value: '~519 ml', label: 'water per 100-word AI prompt', source: 'eesiWater' },
    { value: '~2.9 Wh', label: 'IEA estimate: a ChatGPT query', source: 'sbsNews' },
    { value: '~0.3 Wh', label: 'a Google search (de Vries)', source: 'devries' },
  ],

  trainingEmbodied: [
    { value: '~284 t CO2e', label: 'training a large transformer (GPT-3-era)', source: 'strubell2019' },
    { value: '~700,000 L', label: 'water to train GPT-3 (estimated)', source: 'thirsty' },
    { value: '~20% of lifecycle', label: 'typical share of embodied (hardware) carbon in a model footprint', source: 'llmcarbon' },
    { value: '80-90%', label: 'share of AI energy spent on inference, not training (UNU-INWEH)', source: 'unricAi' },
  ],

  headlineRefs: [
    { label: 'Google search (de Vries 2023)', value: 0.3, unit: 'Wh', source: 'devries' },
    { label: 'ChatGPT query (IEA via SBS, 2024)', value: 2.9, unit: 'Wh', source: 'sbsNews' },    { label: 'ChatGPT query (Altman counter-claim)', value: 0.34, unit: 'Wh', source: 'sbsNews' },
    { label: 'ChatGPT avg CO2e (Cloud Carbon Footprint 2024)', value: 8.3, unit: 'g', source: 'cloudCarbon' },
    { label: 'GPT-3.5 query CO2e (Cloud Carbon Footprint 2024)', value: 4, unit: 'g', source: 'cloudCarbon' },
    { label: 'GPT-4 query CO2e (Cloud Carbon Footprint 2024)', value: 15, unit: 'g', source: 'cloudCarbon' },
    { label: 'ChatGPT water, per prompt (Li et al. 2023)', value: 15, unit: 'ml', source: 'thirsty' },
    { label: '100-word AI prompt water (UC Riverside / EESI)', value: 519, unit: 'ml', source: 'eesiWater' },
    { label: 'Data centre avg WUE (direct only)', value: 1.9, unit: 'L/kWh', source: 'eesiWater' },
    { label: 'Data centre total WUE (direct + indirect)', value: 5.3, unit: 'L/kWh', source: 'cellReports' },
    { label: 'AI share of DC electricity, end-2024 (de Vries-Gao)', value: 20, unit: '%', source: 'cellReports' },
    { label: 'AI power demand (2024 -> 2025, de Vries-Gao)', value: 23, unit: 'GW', source: 'cellReports' },
    { label: 'AI carbon footprint 2025 (de Vries-Gao)', value: 79.7, unit: 'Mt CO2', source: 'cellReports' },
    { label: 'AI water footprint 2025 (de Vries-Gao)', value: 764.6, unit: 'B L', source: 'cellReports' },
    { label: 'US DC grid carbon intensity (LBNL 2024)', value: 0.46, unit: 't CO2/MWh', source: 'cellReports' },
    { label: 'Chat query vs text classification (UNU-INWEH 2026)', value: 200, unit: 'x', source: 'unricAi' },
    { label: 'AI image vs text classification (UNU-INWEH 2026)', value: 1450, unit: 'x', source: 'unricAi' },
    { label: 'AI image water footprint (UNU-INWEH 2026)', value: 29, unit: 'ml', source: 'unricAi' },
    { label: 'Indirect vs direct DC water, US (LBNL 2024 via WSJ)', value: 12, unit: 'x', source: 'wsjWater' },
    { label: 'ChatGPT daily prompts (UNU-INWEH 2026)', value: 2.5, unit: 'B', source: 'unricAi' },
    { label: 'Global DC electricity 2030 (IEA / UNU-INWEH)', value: 945, unit: 'TWh', source: 'unricAi' },
    { label: 'Global DC electricity 2025 (UNU-INWEH)', value: 448, unit: 'TWh', source: 'unricAi' },
  ],

  macro: {
    globalDcElectricity: [
      { year: 2024, tWh: 415, note: 'measured / IEA 2025' },
      { year: 2025, tWh: 470, note: 'interpolated' },
      { year: 2026, tWh: 540, note: 'interpolated' },
      { year: 2027, tWh: 615, note: 'interpolated' },
      { year: 2028, tWh: 700, note: 'interpolated' },
      { year: 2029, tWh: 800, note: 'interpolated' },
      { year: 2030, tWh: 945, note: 'projected / IEA 2025' },
    ],
    bigSixFirms: [
      { year: 2024, low: 118, high: 118, note: 'measured' },
      { year: 2030, low: 239, high: 295, note: 'projected' },
    ],
    waterBenchmark2030TrillionL: 9.3,
    macroWaterNotes: [
      { text: 'Derived global data-centre water = electricity (TWh) x total WUE (~5.3 L/kWh, direct + indirect) -> ~2.2 trillion L (2024) rising to ~5.0 trillion L (2030).', sources: ['cellReports', 'eesiWater'] },
      { text: 'UNU-INWEH projects a much larger ~9.3 trillion L by 2030 once AI-specific footprint growth is included; the derived line is therefore a conservative lower bound.', sources: ['unricAi'] },
      { text: 'AI water footprint 2025: 312.5-764.6B L, roughly the entire global annual bottled-water market (Patterns 2026).', sources: ['cellReports'] },
      { text: 'Indirect (power-plant) water dominates and is under-reported: ~3.4 L/kWh actual vs ~1.04 L/kWh IEA-implied; only Meta reports it (Patterns 2026 / WSJ).', sources: ['cellReports', 'wsjWater'] },
    ],
    macroNotes: [
      { text: 'Global data-center electricity projected to roughly double from ~415 TWh (2024) to ~945 TWh (2030); AI workloads drive a disproportionate share (IEA 2025, arXiv:2601.06063).', sources: ['ieaEnergyAI', 'aiServers'] },
      { text: 'Six leading AI firms alone: ~118 TWh (2024) rising to 239-295 TWh (2030), concentrated in North America, Western Europe and Asia-Pacific (arXiv:2604.06198).', sources: ['concentratedSiting'] },
      { text: 'AI workloads could account for 50-70% of data-center electricity by 2030 (modeling assumption, arXiv:2506.17284).', sources: ['ieaEnergyAI'] },
      { text: 'Edge-resident inference for 1B daily users could save ~19 TWh/yr and ~7.3 Mt CO2 vs centralized practice (arXiv:2608.02608).', sources: ['edgeNative'] },
      { text: 'US AI servers: +200-300B gallons of water/yr and +24-44 Mt CO2e by 2030 (arXiv:2601.06063).', sources: ['aiServers'] },
      { text: 'UNU-INWEH: inference, not training, is ~80-90% of AI energy use; ChatGPT alone ~2.5B prompts/day ~383 GWh/yr. 2030 water footprint ~9.3 trillion L (UNRIC).', sources: ['unricAi'] },
      { text: 'Reported data-centre water undercounts: US indirect water (at the power plants) is ~12x the direct figure, and only Meta reports it (WSJ / LBNL 2024).', sources: ['wsjWater'] },
      { text: 'Indirect (electricity-embedded) water is the dominant, undercounted component: IEA-implied ~1.04 L/kWh vs ~3.40 L/kWh actual (Apple+Meta+Google US, 2023); Meta ~3.92 L/kWh, Google ~2.97 L/kWh (Patterns 2026).', sources: ['cellReports', 'wsjWater'] },
      { text: 'AI is ~15-20% of total data-center electricity at end-2024, with AI power demand at 9.4 GW rising to 23 GW through 2025 (Patterns 2026).', sources: ['cellReports'] },
    ],
  },

  equivalents: {
    smartphoneChargeWh: 15,
    carGPerKm: 170,
    coffeeG: 21,
    streamingHourWh: 100,
    ledBulbW: 9,
    treeGPerYear: 21000,
    waterBottleMl: 500,
  },

  waterModel: {
    wueLPerKWh: 1.9,
    wueSource: 'eesiWater',
    indirectLPerKWh: 3.4,
    indirectSource: 'cellReports',
    promptWaterPer100WordsMl: 519,
    promptWaterSource: 'eesiWater',
    promptWordsPerQuery: 300,
  },

  auContext: {
    expectations: [
      { n: 1, title: "Prioritise Australia's national interest", desc: 'National security, data sovereignty, social licence, protecting sensitive data.' },
      { n: 2, title: "Support Australia's energy transition", desc: 'Underwrite new renewable supply/storage, pay full grid-connection share, minimise demand and emissions.' },
      { n: 3, title: 'Sustainable and efficient water usage', desc: 'Efficient cooling, non-potable/recycled water, transparent water reporting.' },
      { n: 4, title: 'Invest in Australian skills and workforce', desc: 'Fair, safe, well-paid jobs; apprenticeships and structured training.' },
      { n: 5, title: 'Strengthen research, innovation and local capability', desc: 'Affordable compute access for start-ups, researchers and not-for-profits.' },
    ],
    notes: [
      { text: 'Guidelines are expectations, not law - experts warn companies could "cut corners" on energy and water (SBS News).', sources: ['sbsNews'] },
      { text: 'Australia data centres use ~2% of grid-supplied electricity; projected to triple to ~6% by 2030 (SBS News).', sources: ['sbsNews'] },
      { text: 'Australia has the second-largest data centre construction pipeline in the world, after the US (SBS News).', sources: ['sbsNews'] },
      { text: 'Federal agencies require NABERS 5-star rating for hosted data centres; no such requirement for private builds (SBS News).', sources: ['sbsNews'] },
      { text: 'The government will deprioritise non-genuine proposals that congest approval pathways (industry.gov.au).', sources: ['industryAu'] },
    ],
    sources: ['industryAu', 'sbsNews', 'conversation'],
  },

  rightToolForTask: [
    { task: 'A quick factual question', best: 'Web search / search engine', cost: 1, why: 'AI chatbots use ~10x the energy of a Google search per query (IEA via SBS).' },
    { task: 'A short, simple sentence polish', best: 'Your own brain / spell-checker', cost: 0, why: 'Large-truck-for-one-envelope: outcome identical, far less compute.' },
    { task: 'Math or calculation', best: 'Calculator / spreadsheet', cost: 0, why: 'Deterministic tools give exact answers with negligible resource use.' },
    { task: 'A one-off summarisation of short text', best: 'Small model / quick AI answer', cost: 2, why: 'Smaller models use far less energy than frontier flagship models.' },
    { task: 'Code review, long analysis, creative draft', best: 'Frontier AI model', cost: 3, why: 'The most justified use of the most resource-intensive models.' },
    { task: 'Images, audio, video generation', best: 'Avoid unless necessary', cost: 3, why: 'Media generation typically requires far more compute than text.' },
  ],

  baselines: [
    {
      id: 'google-search',
      label: 'Google search',
      type: 'number',
      value: 0.3,
      unit: 'Wh',
      source: 'devries',
      note: 'Headline estimate from de Vries 2023 (~0.3 Wh per search).',
    },
    {
      id: 'ecosia-search',
      label: 'Ecosia search',
      type: 'aggregate',
      source: 'ecosiaHome',
      points: [
        'Runs on 100% renewable energy; Ecosia claims to produce about twice as much renewable energy as its searches use.',
        'Claims each Ecosia search "removes 1 kg of CO2" through tree-planting profits (Regeneration Report).',
        'Annual organizational footprint: ~102 t CO2 (audited aggregate, not per-query).',
      ],
      note: 'Ecosia publishes no per-query energy/CO2 figure for a search.',
    },
    {
      id: 'ecosia-ai',
      label: 'Ecosia AI (chat / overviews)',
      type: 'aggregate',
      source: 'ecosiaAi',
      points: [
        'Launched December 2025: AI Overviews + AI Chat, both optional and switchable off.',
        'Uses smaller, more efficient models via a European provider; avoids video generation; no per-query figure published.',
        'Ecosia estimates the AI chatbot raises its CO2 footprint ~5% (~5.1 t on the ~102 t base).',
        'Claims to generate more renewable energy than its AI features use; selects models via AI Energy Score and Ecologits.',
      ],
      note: 'Ecosia publishes no per-query energy/CO2 figure for an AI interaction.',
    },
  ],
};
