const EXAMPLES = [
  {
    group: 'Everyday text',
    desc: 'Write a short email',
    model: 'claude-sonnet-5',
    promptTok: 150,
    outTok: 180,
    note: 'Lightweight, typical everyday query.',
    sources: ['tokensToWh', 'ieaEnergyAI'],
  },
  {
    group: 'Everyday text',
    desc: 'Explain a concept in simple terms',
    model: 'gpt56luna',
    promptTok: 300,
    outTok: 500,
    note: 'Compact reasoning tier, everyday use.',
    sources: ['wattgpu', 'tokensToWh'],
  },
  {
    group: 'Everyday text',
    desc: 'Quick translation (English sentence)',
    model: 'gpt56luna',
    promptTok: 200,
    outTok: 250,
    note: 'Minimal footprint.',
    sources: ['tokensToWh'],
  },
  {
    group: 'Everyday text',
    desc: 'Quick fact-check / classification',
    model: 'gpt56luna',
    promptTok: 120,
    outTok: 60,
    note: 'Tiny output; near-minimal footprint for a chat model.',
    sources: ['tokensToWh'],
  },
  {
    group: 'Everyday text',
    desc: 'Polish / rewrite a paragraph',
    model: 'gpt56sol',
    promptTok: 300,
    outTok: 250,
    note: 'Editing an existing draft is cheaper than writing from scratch.',
    sources: ['tokensToWh', 'vllmConfigs'],
  },
  {
    group: 'Everyday text',
    desc: 'Write a social post / thread',
    model: 'gpt56luna',
    promptTok: 200,
    outTok: 400,
    note: 'Everyday content, small model.',
    sources: ['tokensToWh'],
  },
  {
    group: 'Everyday text',
    desc: 'AI-style search with citations',
    model: 'gpt56sol',
    promptTok: 1500,
    outTok: 800,
    note: 'Blends 0.3 Wh (Google search) vs 2.9 Wh (ChatGPT) headline figures.',
    sources: ['devries', 'sbsNews'],
  },
  {
    group: 'Heavy documents & code',
    desc: 'Summarize a 10-page PDF',
    model: 'gpt56sol',
    promptTok: 24000,
    outTok: 700,
    note: 'Long input, short output - dominated by prefill energy.',
    sources: ['tokensToWh', 'hymell'],
  },
  {
    group: 'Heavy documents & code',
    desc: 'Code review / debug a snippet',
    model: 'gpt56sol',
    promptTok: 1600,
    outTok: 900,
    note: 'Flagship reasoning model, moderate output.',
    sources: ['tokensToWh', 'wattgpu'],
  },
  {
    group: 'Heavy documents & code',
    desc: 'Brainstorm blog post ideas',
    model: 'deepseekv3',
    promptTok: 400,
    outTok: 700,
    note: 'Low-cost MoE model.',
    sources: ['tokensToWh', 'vllmConfigs'],
  },
  {
    group: 'Heavy documents & code',
    desc: 'Long-document Q&A (RAG retrieval)',
    model: 'gpt56sol',
    promptTok: 30000,
    outTok: 1000,
    note: 'Heaviest text case in the token model.',
    sources: ['tokensToWh', 'hymell'],
  },
  {
    group: 'Heavy documents & code',
    desc: 'Draft a full blog post',
    model: 'claude-sonnet-5',
    promptTok: 400,
    outTok: 1200,
    note: 'Long output - decode dominates.',
    sources: ['tokensToWh'],
  },
  {
    group: 'Heavy documents & code',
    desc: 'Translate a long document',
    model: 'gpt56sol',
    promptTok: 6000,
    outTok: 5000,
    note: 'Heavy bidirectional token volume.',
    sources: ['tokensToWh', 'langEnergy'],
  },
  {
    group: 'Vision & media',
    desc: 'Image caption / vision analysis',
    model: 'gemini3',
    promptTok: 1200,
    outTok: 120,
    note: 'Vision tokens count as input.',
    sources: ['tokensToWh', 'powerHungry'],
  },
  {
    group: 'Vision & media',
    desc: 'Describe an uploaded photo',
    model: 'gemini3',
    promptTok: 1500,
    outTok: 80,
    note: 'Vision input; task-specific captioning runs ~0.063 Wh per 1,000 inferences.',
    sources: ['powerHungry'],
  },
  {
    group: 'Vision & media',
    desc: 'Object detection via chat model',
    model: 'gpt56sol',
    promptTok: 2000,
    outTok: 120,
    note: 'Right-tool anti-pattern: a purpose-built detector uses ~0.038 kWh per 1,000 inferences.',
    sources: ['powerHungry'],
  },
  {
    group: 'Vision & media',
    desc: 'Generate one AI image (SDXL-class)',
    model: null,
    modelLabel: 'Diffusion image model',
    fixedWh: 2.9,
    note: '~2.9 Wh per image (mean, Power Hungry Processing). Worst case ~11.5 Wh ~ half a smartphone charge per image.',
    sources: ['powerHungry'],
  },
  {
    group: 'Vision & media',
    desc: 'Generate a short AI video clip',
    model: null,
    modelLabel: 'Text-to-video diffusion',
    fixedWh: 90,
    fixedBaselineMl: 0,
    note: '~90 Wh per short clip (WAN2.1-T2V-1.3B, 720x1280, 81 frames, 50 steps). ~30x more than image generation; a flagship 14B model is ~415 Wh.',
    sources: ['videoEnergy'],
  },
  {
    group: 'Audio',
    desc: 'Transcribe a 1-hour Zoom meeting (multi-speaker)',
    model: null,
    modelLabel: 'Cloud speech-to-text',
    fixedWh: 16,
    fixedCostUsd: 0.36,
    fixedBaselineMl: 0,
    note: '~16 Wh per audio-hour (cloud STT, 0.35 kWh for ~22.2 h of audio). 60 min x $0.006/min = $0.36 (OpenAI/Google list pricing). CO2 and water follow the grid/WUE methodology.',
    sources: ['asrCompare', 'openaiPrice', 'cellReports'],
  },
];
